from enum import Enum
class Family(Enum):
    INDO_EUROPEAN = 1, "Indo-European"
    SINO_TIBETAN =  2, "Sino-Tibetan"
    AFRO_ASIATIC = 3, "Afro-Asiatic"
    AUSTRONESIAN = 4, "Austronesian"
    JAPONIC = 5, "Japonic"
    AUSTROASIATIC = 6, "Austroasiatic"
    DRAVIDIAN = 7, "Dravidian"
    TURKIC = 8 , "Turkic"
    NIGER_CONGO = 9, "Niger-Congo"
    KOREANIC = 10, "Koreanic"
    KRA_DAI = 11, "Kra-Dai"
class Branch(Enum):
    BALTO_SLAVIC = 1, "Balto Slavic"
    BANTU = 2, "Bantu"
    CHADIC = 3, "Chadic"
    GERMANIC = 4, "Germanic"
    INDO_ARYAN = 5, "Indo-Aryan"
    IRANIAN = 6, "Iranian"
    KRIO = 7, "Krio"
    MALAYO_POLYNESIAN = 8, "Malayo-Polynesian"
    OGHUZ = 9, "Oghuz"
    ROMANCE = 10, "Romance"
    SEMITIC = 10, "Semitic"
    SINITIC = 11, "Sinitic"
    SOUTH = 10, "South"
    SOUTH_CENTRAL = 11, "South-Central"
    VIETIC = 12, "Vietic"
    ZHUANG_TAI = 13, "Zhuang-Tai"
class Script(Enum):
    CHINESE = 1, "Chinese"
    ARABIC = 2, "Arabic"
    GURMUKHI = 3, "Gurmukhi"
    JAVANESE = 4, "Javanese"
    LATIN = 5, "Latin"
    SYRIAC = 6, "Syriac"
    BENGALI = 7, "Bengali"
    BAYBAYIN = 8, "Baybayin"
    DEVANAGARI = 9, "Devanagari"
    KANA = 10, "Kana"
    CYRILLIC = 11, "Cyrillic"
    GUJARATI = 12, "Gujarati"
    HANGUL = 13, "Hangul"
    SABA = 14, "Saba"
    TELUGU = 15, "Telugu"
    THAI = 16, "Thai"
    KANNADA = 17, "Kannada"
    TAMIL = 18, "Tamil"

