from enum import Enum
class Family(Enum):
    Indo_European = 1
    Sino_Tibetan =  2
    Afro_Asiatic = 3
    Austronesian = 4
    Japonic = 5
    Austroasiatic = 6
    Dravidian = 7
    Turkic = 8
    Niger_Congo = 9
    Koreanic = 10
    Kra_Dai = 11
class Branch(Enum):
    Balto_Slavic = 1
    Bantu = 2
    Chadic = 3
    Germanic = 4
    Indo_Aryan = 5
    Iranian = 6
    Krio = 7
    Malayo_Polynesian = 8
    Oghuz = 9
    Romance = 10
    Semitic = 11
    Sinitic = 12
    South = 13
    South_Central = 14
    Vietic = 15
    Zhuang_Tai = 16
class Script(Enum):
    Chinese = 1
    Arabic = 2
    Gurmukhi = 3
    Javanese = 4
    Latin = 5
    Syriac = 6
    Bengali= 7
    Baybayin = 8
    Devanagari = 9
    Kana = 10
    Cyrillic = 11
    Gujarati = 12
    Hangul = 13
    Saba = 14
    Telugu = 15
    Thai = 16
    Kannada = 17
    Tamil = 18
