services:
  app:
    build: .
    links:
      - db

  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro