name: Run Pytest

on:
  push:
    branches: [ master ]    # Run tests when pushing to main
  pull_request:
    branches: [ master ]    # Run tests on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # or your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
