name: Run Pytest with MySQL Initialization

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: strongpassword
          MYSQL_DATABASE: languages
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mysql-connector-python

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is up"
              break
            fi
            echo "Waiting for MySQL to start..."
            sleep 1
          done

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Initialize database schema and seed data
        run: |
          for file in ./data/*.sql; do
            echo "Running $file"
            mysql -h 127.0.0.1 -P 3306 -u root -pstrongpassword languages < "$file"
          done


      - name: Run tests
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: strongpassword
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DB: languages
          PYTHONPATH: .
        run: |
          pytest --maxfail=1 --disable-warnings -q
